# Generated by Django 5.0.1 on 2024-05-05 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorta_Waste', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
