# Generated by Django 5.0.1 on 2024-05-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sorta_Waste', '0002_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plastic_waste', models.BooleanField(default=False)),
                ('organic_waste', models.BooleanField(default=False)),
                ('metallic_waste', models.BooleanField(default=False)),
                ('electronic_waste', models.BooleanField(default=False)),
                ('bin_picture', models.ImageField(upload_to='bin_picture/')),
            ],
        ),
    ]
