# Generated by Django 5.0.1 on 2024-05-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorta_Waste', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small', models.BooleanField(default=False)),
                ('mideum', models.BooleanField(default=False)),
                ('Large', models.BooleanField(default=False)),
                ('Super', models.BooleanField(default=False)),
            ],
        ),
    ]
