# Generated by Django 5.0.1 on 2024-05-07 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('sorta_Waste', '0004_wasteamount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wasteamount',
            old_name='Large',
            new_name='large',
        ),
        migrations.RenameField(
            model_name='wasteamount',
            old_name='Super',
            new_name='super',
        ),
        migrations.AddField(
            model_name='wasteamount',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser'),
        ),
        migrations.AddField(
            model_name='wasteorder',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser'),
        ),
    ]
