# Generated by Django 5.0.1 on 2024-05-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorta_Waste', '0005_rename_large_wasteamount_large_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasteorder',
            name='large',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wasteorder',
            name='mideum',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wasteorder',
            name='small',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wasteorder',
            name='super',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='WasteAmount',
        ),
    ]
