# Generated by Django 5.0.1 on 2024-05-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorta_Waste', '0006_wasteorder_large_wasteorder_mideum_wasteorder_small_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wasteorder',
            name='electronic_waste',
        ),
        migrations.RemoveField(
            model_name='wasteorder',
            name='large',
        ),
        migrations.RemoveField(
            model_name='wasteorder',
            name='metallic_waste',
        ),
        migrations.RemoveField(
            model_name='wasteorder',
            name='mideum',
        ),
        migrations.RemoveField(
            model_name='wasteorder',
            name='organic_waste',
        ),
        migrations.RemoveField(
            model_name='wasteorder',
            name='plastic_waste',
        ),
        migrations.RemoveField(
            model_name='wasteorder',
            name='small',
        ),
        migrations.RemoveField(
            model_name='wasteorder',
            name='super',
        ),
        migrations.AddField(
            model_name='wasteorder',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('super', 'Super')], default='small', max_length=10),
        ),
        migrations.AddField(
            model_name='wasteorder',
            name='waste_type',
            field=models.CharField(choices=[('plastic', 'Plastic Waste'), ('organic', 'Organic Waste'), ('metallic', 'Metallic Waste'), ('electronic', 'Electronic Waste')], default='plastic', max_length=20),
        ),
    ]
