# Generated by Django 5.0.1 on 2024-05-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorta_Waste', '0007_remove_wasteorder_electronic_waste_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasteorder',
            name='bin_picture',
            field=models.ImageField(blank=True, null=True, upload_to='bin_picture/'),
        ),
        migrations.AlterField(
            model_name='wasteorder',
            name='size',
            field=models.CharField(choices=[('small', '5Kg'), ('medium', '10Kg'), ('large', '15Kg'), ('super', '20Kg')], default='5Kg', max_length=10),
        ),
    ]
