# Generated by Django 5.0.1 on 2024-05-11 23:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorta_Waste', '0008_alter_wasteorder_bin_picture_alter_wasteorder_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasteorder',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
